name: Stray Cog
favicon: null
layout_spectrum: 0.6410124048124999
typography_spectrum: 0.1865495308302343
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#58585a'
    - '#000000'
    - '#ec008c'
    - '#a4a4a5'
  brandStrength: 0.8003257738891989
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
